# permissions for end users to edit revisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: revision-editor-role
rules:
  - apiGroups:
      - core.hedron.build
    resources:
      - revisions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.hedron.build
    resources:
      - revisions/status
    verbs:
      - get
